[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
    'npm ci',
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
    'npm run build'
]

[phases.deploy]
cmds = [
    'chmod +x post-build.sh',
    './post-build.sh'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'